/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/White_single_Low+poly+Car.glb -o src/components/CarWhite.jsx -k -K -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CarWhite(props) {
  const { nodes, materials } = useGLTF('/models/White_single_Low+poly+Car.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="CAR" position={[0, 0.164, 0]}>
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} />
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.002']} />
          <mesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['Material.003']} />
          <mesh name="Cube002_3" geometry={nodes.Cube002_3.geometry} material={materials['Material.007']} />
          <mesh name="Cube002_4" geometry={nodes.Cube002_4.geometry} material={materials.Material} />
          <group name="Lights">
            <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.004']} />
            <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials['Material.005']} />
            <mesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials['Material.006']} />
          </group>
          <group name="Wheels">
            <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.003']} />
            <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Material.004']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/White_single_Low+poly+Car.glb')
