/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/TravelBuddy_LandingPage_Map.glb -o src/components/Map.jsx -k -K -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CartoonMap(props) {
  const { nodes, materials } = useGLTF(
    "/models/TravelBuddy_LandingPage_Map.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          position={[0, 1.633, -2.303]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.8, 4, 4]}
        >
          <mesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={materials["Material.001"]}
            position={[0.877, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.951, 4.753, 0.951]}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/TravelBuddy_LandingPage_Map.glb");
